/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TecnologiasRouteImport } from './routes/tecnologias'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as ImagensRouteImport } from './routes/imagens'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as CriarSenhaRouteImport } from './routes/criar-senha'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiasRoute = TecnologiasRouteImport.update({
  id: '/tecnologias',
  path: '/tecnologias',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagensRoute = ImagensRouteImport.update({
  id: '/imagens',
  path: '/imagens',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarSenhaRoute = CriarSenhaRouteImport.update({
  id: '/criar-senha',
  path: '/criar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/criar-senha': typeof CriarSenhaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/imagens': typeof ImagensRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/registro': typeof RegistroRoute
  '/tecnologias': typeof TecnologiasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/criar-senha': typeof CriarSenhaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/imagens': typeof ImagensRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/registro': typeof RegistroRoute
  '/tecnologias': typeof TecnologiasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/criar-senha': typeof CriarSenhaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/imagens': typeof ImagensRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/registro': typeof RegistroRoute
  '/tecnologias': typeof TecnologiasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/criar-senha'
    | '/esqueci-senha'
    | '/imagens'
    | '/indicadores'
    | '/login'
    | '/projetos'
    | '/registro'
    | '/tecnologias'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/criar-senha'
    | '/esqueci-senha'
    | '/imagens'
    | '/indicadores'
    | '/login'
    | '/projetos'
    | '/registro'
    | '/tecnologias'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/criar-senha'
    | '/esqueci-senha'
    | '/imagens'
    | '/indicadores'
    | '/login'
    | '/projetos'
    | '/registro'
    | '/tecnologias'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  CriarSenhaRoute: typeof CriarSenhaRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  ImagensRoute: typeof ImagensRoute
  IndicadoresRoute: typeof IndicadoresRoute
  LoginRoute: typeof LoginRoute
  ProjetosRoute: typeof ProjetosRoute
  RegistroRoute: typeof RegistroRoute
  TecnologiasRoute: typeof TecnologiasRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologias': {
      id: '/tecnologias'
      path: '/tecnologias'
      fullPath: '/tecnologias'
      preLoaderRoute: typeof TecnologiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagens': {
      id: '/imagens'
      path: '/imagens'
      fullPath: '/imagens'
      preLoaderRoute: typeof ImagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-senha': {
      id: '/criar-senha'
      path: '/criar-senha'
      fullPath: '/criar-senha'
      preLoaderRoute: typeof CriarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRoute,
  CriarSenhaRoute: CriarSenhaRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  ImagensRoute: ImagensRoute,
  IndicadoresRoute: IndicadoresRoute,
  LoginRoute: LoginRoute,
  ProjetosRoute: ProjetosRoute,
  RegistroRoute: RegistroRoute,
  TecnologiasRoute: TecnologiasRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
